// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: awe.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for Post method
type PostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostRequest) Reset() {
	*x = PostRequest{}
	mi := &file_awe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostRequest) ProtoMessage() {}

func (x *PostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_awe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostRequest.ProtoReflect.Descriptor instead.
func (*PostRequest) Descriptor() ([]byte, []int) {
	return file_awe_proto_rawDescGZIP(), []int{0}
}

func (x *PostRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// Response message for Post method
type PostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostResponse) Reset() {
	*x = PostResponse{}
	mi := &file_awe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostResponse) ProtoMessage() {}

func (x *PostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_awe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostResponse.ProtoReflect.Descriptor instead.
func (*PostResponse) Descriptor() ([]byte, []int) {
	return file_awe_proto_rawDescGZIP(), []int{1}
}

func (x *PostResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PostResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request message for Stream method
type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"` // Optional field to specify how many responses to stream
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_awe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_awe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_awe_proto_rawDescGZIP(), []int{2}
}

func (x *StreamRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// Response message for Stream method
type StreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          int32                  `protobuf:"varint,1,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_awe_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_awe_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_awe_proto_rawDescGZIP(), []int{3}
}

func (x *StreamResponse) GetData() int32 {
	if x != nil {
		return x.Data
	}
	return 0
}

func (x *StreamResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_awe_proto protoreflect.FileDescriptor

const file_awe_proto_rawDesc = "" +
	"\n" +
	"\tawe.proto\x12\x03awe\"!\n" +
	"\vPostRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"B\n" +
	"\fPostResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"%\n" +
	"\rStreamRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"B\n" +
	"\x0eStreamResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\x05R\x04data\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp2r\n" +
	"\n" +
	"AWEService\x12-\n" +
	"\x04Post\x12\x10.awe.PostRequest\x1a\x11.awe.PostResponse\"\x00\x125\n" +
	"\x06Stream\x12\x12.awe.StreamRequest\x1a\x13.awe.StreamResponse\"\x000\x01B(Z&github.com/alan-mat/awe/internal/protob\x06proto3"

var (
	file_awe_proto_rawDescOnce sync.Once
	file_awe_proto_rawDescData []byte
)

func file_awe_proto_rawDescGZIP() []byte {
	file_awe_proto_rawDescOnce.Do(func() {
		file_awe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_awe_proto_rawDesc), len(file_awe_proto_rawDesc)))
	})
	return file_awe_proto_rawDescData
}

var file_awe_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_awe_proto_goTypes = []any{
	(*PostRequest)(nil),    // 0: awe.PostRequest
	(*PostResponse)(nil),   // 1: awe.PostResponse
	(*StreamRequest)(nil),  // 2: awe.StreamRequest
	(*StreamResponse)(nil), // 3: awe.StreamResponse
}
var file_awe_proto_depIdxs = []int32{
	0, // 0: awe.AWEService.Post:input_type -> awe.PostRequest
	2, // 1: awe.AWEService.Stream:input_type -> awe.StreamRequest
	1, // 2: awe.AWEService.Post:output_type -> awe.PostResponse
	3, // 3: awe.AWEService.Stream:output_type -> awe.StreamResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_awe_proto_init() }
func file_awe_proto_init() {
	if File_awe_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_awe_proto_rawDesc), len(file_awe_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_awe_proto_goTypes,
		DependencyIndexes: file_awe_proto_depIdxs,
		MessageInfos:      file_awe_proto_msgTypes,
	}.Build()
	File_awe_proto = out.File
	file_awe_proto_goTypes = nil
	file_awe_proto_depIdxs = nil
}
